from __future__ import annotations

from typing import Final

from .reference_data import (
    ReferenceScenarioRecord,
)
from .types import (
    AftermathState,
    CompatibilityState,
    GateState,
    LockState,
    NodeState,
)

CGTLIB_STABLE_API: Final[tuple[str, ...]] = (
    "CGTParameters",
    "PhaseState",
    "StructuralTransitionReport",
    "evaluate_fate_vector",
    "classify_existence_rank",
    "compute_fate_balance",
    "compute_flourishing_potential",
    "compute_extinction_indicator",
    "compute_stability_indicator",
    "compute_distortion_indicator",
    "compute_hybridity_indicator",
    "compute_repeatability",
    "evaluate_dynamic_lift",
    "compute_dynamic_lift",
    "evaluate_possibility",
    "compute_constrained_possibility",
    "evaluate_existence",
    "compute_existential_score",
    "ExistenceRank",
    "FateVector",
    "DynamicLiftState",
    "PossibilityState",
    "ExistenceState",
    "StructuralTransitionInput",
    "ScenarioPack",
    "ScenarioPackResult",
    "SensitivityReport",
    "SensitivitySnapshot",
    "BenchmarkSurface",
    "BenchmarkSurfacePoint",
    "RobustnessReport",
    "RobustnessProfile",
    "ComparativeEnvelope",
    "ComparativeEnvelopeReport",
    "StressRegime",
    "RegimeClassification",
    "RegimeClassifierReport",
    "TransitionArchetype",
    "TrajectoryMap",
    "TrajectoryMapPoint",
    "build_cgtlib_manifest",
    "canonical_phase_state",
    "canonical_transition_input",
    "canonical_scenario_pack",
    "compute_delay_gate",
    "compute_transition_channel",
    "compute_transmissibility",
    "compute_retention",
    "compute_phase_mass",
    "compute_self_potential",
    "evaluate_lock_state",
    "evaluate_locking",
    "evaluate_compatibility",
    "evaluate_aftermath",
    "evaluate_continuation",
    "evaluate_structural_transition",
    "simulate_delay_progression",
    "simulate_transition_series",
    "evaluate_transition_batch",
    "summarize_transition_batch",
    "validate_transition_batch_inputs",
    "validate_parameters",
    "validate_phase_state",
    "validate_structural_transition_report",
    "validate_scenario_pack",
    "evaluate_scenario_pack",
    "evaluate_scenario_packs",
    "summarize_scenario_packs",
    "list_reference_dataset_ids",
    "load_reference_scenario_record",
    "load_all_reference_scenario_records",
    "load_reference_scenario_packs",
    "list_canonical_scenario_catalog",
    "build_canonical_scenario_pack",
    "build_all_canonical_scenario_packs",
    "evaluate_parameter_sensitivity",
    "summarize_sensitivity_report",
    "evaluate_benchmark_surface",
    "evaluate_benchmark_surfaces",
    "summarize_benchmark_surface",
    "evaluate_multi_axis_robustness",
    "summarize_robustness_report",
    "list_canonical_robustness_profiles",
    "load_canonical_robustness_profile",
    "evaluate_canonical_robustness_profile",
    "evaluate_all_canonical_robustness_profiles",
    "evaluate_comparative_envelopes",
    "summarize_comparative_envelopes",
    "list_canonical_stress_regimes",
    "load_canonical_stress_regime",
    "evaluate_canonical_stress_regime",
    "evaluate_all_canonical_stress_regimes",
    "classify_robustness_report",
    "classify_comparative_envelopes",
    "evaluate_canonical_regime_classifier_report",
    "list_canonical_transition_archetypes",
    "load_canonical_transition_archetype",
    "evaluate_canonical_transition_archetype",
    "evaluate_all_canonical_transition_archetypes",
    "summarize_transition_archetype",
    "summarize_all_transition_archetypes",
    "evaluate_regime_trajectory_map",
    "summarize_trajectory_map",
)


def build_public_api_snapshot() -> dict[str, object]:
    return {
        "library": "cgtlib",
        "surface": "stable-api",
        "symbol_count": len(CGTLIB_STABLE_API),
        "symbols": list(CGTLIB_STABLE_API),
    }


__all__ = list(CGTLIB_STABLE_API) + [
    "AftermathState",
    "CompatibilityState",
    "GateState",
    "LockState",
    "NodeState",
    "ReferenceScenarioRecord",
    "build_public_api_snapshot",
]
