from __future__ import annotations

from decimal import Decimal

from processual_api.billing.maestro_calibration_contracts import (
    CalibrationQuantities,
    CalibrationWorkload,
    MaestroBillingDisposition,
    MaestroFailureOwner,
    MaestroResourceBand,
    MaestroTaskFamily,
)

D = Decimal


def _q(**kwargs: str) -> CalibrationQuantities:
    defaults = {
        "base_executions": "0",
        "integration_actions": "0",
        "equivalent_pages": "0",
        "records_processed": "0",
        "verification_items": "0",
        "standard_supervision_gates": "0",
        "extended_supervision_gates": "0",
        "excess_storage_gb_month": "0",
    }
    defaults.update(kwargs)
    return CalibrationQuantities(**{key: D(value) for key, value in defaults.items()})


def _w(
    workload_id: str,
    title: str,
    family: MaestroTaskFamily,
    quantities: CalibrationQuantities,
    raw: str,
    settled: str,
    *,
    band: MaestroResourceBand = MaestroResourceBand.NORMAL,
    owner: MaestroFailureOwner = MaestroFailureOwner.NONE,
    disposition: MaestroBillingDisposition = MaestroBillingDisposition.SETTLED,
    notes: str = "",
) -> CalibrationWorkload:
    return CalibrationWorkload(
        workload_id=workload_id,
        title=title,
        task_family=family,
        quantities=quantities,
        resource_band=band,
        expected_failure_owner=owner,
        expected_disposition=disposition,
        expected_raw_units=D(raw),
        expected_settled_units=D(settled),
        notes=notes,
    )


REFERENCE_WORKLOADS: tuple[CalibrationWorkload, ...] = (
    _w(
        "AUT-S-01",
        "Simple successful automation",
        MaestroTaskFamily.AUTOMATION_EXECUTION,
        _q(base_executions="1"),
        "1",
        "1",
    ),
    _w(
        "AUT-M-01",
        "Medium automation",
        MaestroTaskFamily.AUTOMATION_EXECUTION,
        _q(base_executions="1", integration_actions="4", verification_items="25"),
        "3",
        "3",
    ),
    _w(
        "AUT-L-01",
        "Large supervised automation",
        MaestroTaskFamily.AUTOMATION_EXECUTION,
        _q(
            base_executions="1",
            integration_actions="12",
            verification_items="75",
            standard_supervision_gates="1",
        ),
        "9",
        "11.25",
        band=MaestroResourceBand.HEAVY,
    ),
    _w(
        "AUT-F-01",
        "Platform failure before completion",
        MaestroTaskFamily.AUTOMATION_EXECUTION,
        _q(),
        "0",
        "0",
        owner=MaestroFailureOwner.PLATFORM,
        disposition=MaestroBillingDisposition.NON_BILLABLE,
    ),
    _w(
        "AUT-R-01",
        "Internal retry with one final settlement",
        MaestroTaskFamily.AUTOMATION_EXECUTION,
        _q(base_executions="1"),
        "1",
        "1",
        notes="Internal retries must not duplicate settlement.",
    ),
    _w(
        "INT-S-01",
        "Single successful integration action",
        MaestroTaskFamily.INTEGRATION_OPERATION,
        _q(integration_actions="1"),
        "0.25",
        "0.25",
    ),
    _w(
        "INT-M-01",
        "Four successful integration actions",
        MaestroTaskFamily.INTEGRATION_OPERATION,
        _q(integration_actions="4"),
        "1",
        "1",
    ),
    _w(
        "INT-L-01",
        "Twenty successful integration actions",
        MaestroTaskFamily.INTEGRATION_OPERATION,
        _q(integration_actions="20"),
        "5",
        "5",
    ),
    _w(
        "INT-P-01",
        "Five of eight integration actions completed",
        MaestroTaskFamily.INTEGRATION_OPERATION,
        _q(integration_actions="5"),
        "1.25",
        "1.25",
        owner=MaestroFailureOwner.EXTERNAL_PROVIDER,
        notes="Only successful actions are represented.",
    ),
    _w(
        "INT-D-01",
        "Duplicate webhook replay",
        MaestroTaskFamily.INTEGRATION_OPERATION,
        _q(),
        "0",
        "0",
        disposition=MaestroBillingDisposition.NON_BILLABLE,
    ),
    _w(
        "DOC-S-01",
        "Ten clean equivalent pages",
        MaestroTaskFamily.DOCUMENT_PROCESSING,
        _q(equivalent_pages="10"),
        "0.4",
        "0.4",
    ),
    _w(
        "DOC-M-01",
        "Fifty clean equivalent pages",
        MaestroTaskFamily.DOCUMENT_PROCESSING,
        _q(equivalent_pages="50"),
        "2",
        "2",
    ),
    _w(
        "DOC-C-01",
        "Fifty complex-layout pages",
        MaestroTaskFamily.DOCUMENT_PROCESSING,
        _q(equivalent_pages="62.5"),
        "2.5",
        "2.5",
    ),
    _w(
        "DOC-OCR-01",
        "Fifty OCR pages",
        MaestroTaskFamily.DOCUMENT_PROCESSING,
        _q(equivalent_pages="75"),
        "3",
        "3",
    ),
    _w(
        "DOC-P-01",
        "Sixty of one hundred pages completed",
        MaestroTaskFamily.DOCUMENT_PROCESSING,
        _q(equivalent_pages="60"),
        "2.4",
        "2.4",
        owner=MaestroFailureOwner.EXTERNAL_PROVIDER,
    ),
    _w(
        "DOC-F-01",
        "Invalid customer file before work",
        MaestroTaskFamily.DOCUMENT_PROCESSING,
        _q(),
        "0",
        "0",
        owner=MaestroFailureOwner.CUSTOMER,
        disposition=MaestroBillingDisposition.NON_BILLABLE,
    ),
    _w(
        "DAT-S-01",
        "Two hundred fifty records",
        MaestroTaskFamily.DATA_TRANSFORMATION,
        _q(records_processed="250"),
        "0.25",
        "0.25",
    ),
    _w(
        "DAT-M-01",
        "One thousand records",
        MaestroTaskFamily.DATA_TRANSFORMATION,
        _q(records_processed="1000"),
        "1",
        "1",
    ),
    _w(
        "DAT-L-01",
        "Ten thousand records",
        MaestroTaskFamily.DATA_TRANSFORMATION,
        _q(records_processed="10000"),
        "10",
        "10",
    ),
    _w(
        "DAT-H-01",
        "Five thousand heavy records",
        MaestroTaskFamily.DATA_TRANSFORMATION,
        _q(records_processed="5000"),
        "5",
        "6.25",
        band=MaestroResourceBand.HEAVY,
    ),
    _w(
        "DAT-P-01",
        "Seven thousand two hundred records completed",
        MaestroTaskFamily.DATA_TRANSFORMATION,
        _q(records_processed="7200"),
        "7.2",
        "7.2",
        owner=MaestroFailureOwner.EXTERNAL_PROVIDER,
    ),
    _w(
        "VER-S-01",
        "Ten verification items",
        MaestroTaskFamily.VERIFICATION_REVIEW,
        _q(verification_items="10"),
        "0.4",
        "0.4",
    ),
    _w(
        "VER-M-01",
        "Twenty-five verification items",
        MaestroTaskFamily.VERIFICATION_REVIEW,
        _q(verification_items="25"),
        "1",
        "1",
    ),
    _w(
        "VER-L-01",
        "Two hundred fifty verification items",
        MaestroTaskFamily.VERIFICATION_REVIEW,
        _q(verification_items="250"),
        "10",
        "10",
    ),
    _w(
        "VER-MIX-01",
        "Execution with fifty verifications",
        MaestroTaskFamily.VERIFICATION_REVIEW,
        _q(base_executions="1", verification_items="50"),
        "3",
        "3",
    ),
    _w(
        "SUP-S-01",
        "One standard supervision gate",
        MaestroTaskFamily.SUPERVISED_PROJECT,
        _q(standard_supervision_gates="1"),
        "2",
        "2",
    ),
    _w(
        "SUP-E-01",
        "One extended supervision gate",
        MaestroTaskFamily.SUPERVISED_PROJECT,
        _q(extended_supervision_gates="1"),
        "5",
        "5",
    ),
    _w(
        "SUP-M-01",
        "Two standard supervision gates",
        MaestroTaskFamily.SUPERVISED_PROJECT,
        _q(standard_supervision_gates="2"),
        "4",
        "4",
    ),
    _w(
        "SUP-HUM-01",
        "Specialist human review",
        MaestroTaskFamily.SUPERVISED_PROJECT,
        _q(),
        "0",
        "0",
        disposition=MaestroBillingDisposition.NON_BILLABLE,
        notes="Classified as professional service, not Maestro Units.",
    ),
    _w(
        "MIX-S-01",
        "Small mixed workload",
        MaestroTaskFamily.RESEARCH_SYNTHESIS,
        _q(base_executions="1", equivalent_pages="25", integration_actions="4"),
        "3",
        "3",
    ),
    _w(
        "MIX-M-01",
        "Medium mixed workload",
        MaestroTaskFamily.RESEARCH_SYNTHESIS,
        _q(
            base_executions="1",
            equivalent_pages="50",
            integration_actions="8",
            verification_items="50",
            standard_supervision_gates="1",
        ),
        "9",
        "9",
    ),
    _w(
        "MIX-H-01",
        "Heavy mixed workload",
        MaestroTaskFamily.RESEARCH_SYNTHESIS,
        _q(
            base_executions="1",
            equivalent_pages="100",
            integration_actions="12",
            verification_items="50",
            standard_supervision_gates="1",
        ),
        "12",
        "15",
        band=MaestroResourceBand.HEAVY,
    ),
    _w(
        "MIX-X-01",
        "Custom workload beyond v1 cap",
        MaestroTaskFamily.RESEARCH_SYNTHESIS,
        _q(),
        "0",
        "0",
        band=MaestroResourceBand.CUSTOM,
        disposition=MaestroBillingDisposition.REVIEW_REQUIRED,
    ),
    _w(
        "MIX-C-01",
        "Cancellation before execution",
        MaestroTaskFamily.RESEARCH_SYNTHESIS,
        _q(),
        "0",
        "0",
        disposition=MaestroBillingDisposition.RELEASED,
    ),
    _w(
        "MIX-C-02",
        "Cancellation after partial completion",
        MaestroTaskFamily.RESEARCH_SYNTHESIS,
        _q(base_executions="1", equivalent_pages="25"),
        "2",
        "2",
        owner=MaestroFailureOwner.CUSTOMER,
    ),
    _w(
        "MIX-U-01",
        "Unknown failure requiring review",
        MaestroTaskFamily.RESEARCH_SYNTHESIS,
        _q(),
        "0",
        "0",
        owner=MaestroFailureOwner.UNKNOWN,
        disposition=MaestroBillingDisposition.REVIEW_REQUIRED,
    ),
)


def workloads_by_id() -> dict[str, CalibrationWorkload]:
    return {workload.workload_id: workload for workload in REFERENCE_WORKLOADS}
