apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: processual-maestro
  namespace: processual
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: api.processual-maestro.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: processual-maestro
                port:
                  number: 8000
