apiVersion: v1
kind: Service
metadata:
  name: processual-maestro
  namespace: processual
  labels:
    app: processual-maestro
spec:
  selector:
    app: processual-maestro
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
