apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: processual-maestro
  namespace: processual
  labels:
    app: processual-maestro
spec:
  selector:
    matchLabels:
      app: processual-maestro
  endpoints:
    - port: http
      interval: 15s
      path: /metrics
  namespaceSelector:
    matchNames:
      - processual
